version: 2
jobs:
  build:
    docker:
      - image: library/erlang:20.2.4
    steps:
      - checkout
      - run:
          name: vulkan api
          command: apt-get update && apt-get install libvulkan-dev -y
      - run:
          name: rust compiler
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: compile
          command: source $HOME/.cargo/env && rebar3 compile
