version: 2
jobs:
  build:
    docker:
      - image: regikul/plain_vulkan-build_env:0.0.2
    steps:
      - checkout
      - run:
          name: compile
          command: source $HOME/.cargo/env && rebar3 compile
