version: 2
jobs:
  build:
    docker:
      - image: library/erlang:20.2.4
    steps:
      - checkout
      - run:
          name: vulkan api
          command: apt-get update && apt-get install libvulkan-dev
      - run:
          name: compile
          command: rebar3 compile