[package]
name = "plain_vulkan"
version = "0.1.0"
authors = ["Maksim Krzhemenevskiy <regikul@gmail.com>"]

[lib]
name = "plain_vulkan"
crate_type = ["dylib"]


[dependencies]
rustler = "0.21.1"
rustler_codegen = "0.21.1"
lazy_static = "1.0.0"
vk-sys = "0.3.3"
